# Generated by Django 4.2 on 2023-04-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_total',
        ),
    ]
