# Generated by Django 4.2 on 2023-04-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_alter_collection_unique_together_and_more'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='WatchPhoto',
        ),
    ]
