# Generated by Django 4.2 on 2023-04-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='watches.watch'),
        ),
    ]
