# Generated by Django 4.2.2 on 2023-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
