# Generated by Django 4.2.2 on 2023-07-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
