# Generated by Django 4.2 on 2023-04-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_order_and_more'),
        ('products', '0006_product_available'),
        ('reviews', '0002_review_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order', 'product')},
        ),
    ]
