# Generated by Django 4.2 on 2023-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_cost',
            new_name='sub_total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
