# Generated by Django 4.2 on 2023-04-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_values',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
