# Generated by Django 4.2 on 2023-04-11 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('is_waterproof', models.BooleanField(default=False)),
                ('has_date_indicator', models.BooleanField(default=False)),
                ('has_cronograph_features', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('D', 'DARK'), ('L', 'LIGHT'), ('F', 'COLOURFUL')], max_length=1)),
                ('diameter', models.IntegerField(help_text='Watch diameter in mm')),
                ('movement', models.CharField(choices=[('Q', 'QUARTZ'), ('A', 'AUTOMATIC'), ('S', 'SOLAR')], max_length=1)),
                ('case_material', models.CharField(choices=[('M-W', 'METAL-WOOD'), ('W', 'WOOD'), ('M', 'METAL')], max_length=3)),
                ('bracelet_material', models.CharField(choices=[('M-W', 'METAL-WOOD'), ('S-M', 'STONE-METAL'), ('M', 'METAL'), ('W', 'WOOD'), ('L', 'LETHER')], max_length=3)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='watches.collection')),
            ],
        ),
    ]
