# Generated by Django 4.2 on 2023-04-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_alter_watch_collection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'brand')},
        ),
        migrations.AlterUniqueTogether(
            name='watch',
            unique_together={('collection', 'model_name')},
        ),
    ]
