# Generated by Django 4.2 on 2023-04-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
