# Generated by Django 4.2.2 on 2023-07-24 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_products', to='products.product')),
            ],
        ),
    ]
